// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PizzAPIe.Data.Models;

namespace PizzAPIe.Migrations
{
    [DbContext(typeof(PizzaContext))]
    [Migration("20181016061732_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("Relational:Sequence:dbo.NextOrderNumber", "'NextOrderNumber', 'dbo', '1000', '2', '', '', 'Int32', 'False'")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PizzAPIe.Data.Models.Cheese", b =>
                {
                    b.Property<string>("ID");

                    b.Property<string>("Description");

                    b.Property<double>("UnitPrice");

                    b.HasKey("ID");

                    b.ToTable("Cheeses");
                });

            modelBuilder.Entity("PizzAPIe.Data.Models.Order", b =>
                {
                    b.Property<int>("OrderNumber")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("NEXT VALUE FOR dbo.NextOrderNumber");

                    b.Property<string>("CheeseID");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.Property<double>("Price");

                    b.Property<int>("Quantity");

                    b.Property<string>("SauceID");

                    b.Property<string>("SizeID");

                    b.Property<DateTime>("Time");

                    b.Property<string>("ToppingID");

                    b.HasKey("OrderNumber");

                    b.HasIndex("CheeseID");

                    b.HasIndex("SauceID");

                    b.HasIndex("SizeID");

                    b.HasIndex("ToppingID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PizzAPIe.Data.Models.Sauce", b =>
                {
                    b.Property<string>("ID");

                    b.Property<string>("Description");

                    b.Property<double>("UnitPrice");

                    b.HasKey("ID");

                    b.ToTable("Sauces");
                });

            modelBuilder.Entity("PizzAPIe.Data.Models.Size", b =>
                {
                    b.Property<string>("ID");

                    b.Property<string>("Description");

                    b.Property<double>("UnitPrice");

                    b.HasKey("ID");

                    b.ToTable("Sizes");
                });

            modelBuilder.Entity("PizzAPIe.Data.Models.Topping", b =>
                {
                    b.Property<string>("ID");

                    b.Property<string>("Description");

                    b.Property<double>("UnitPrice");

                    b.HasKey("ID");

                    b.ToTable("Toppings");
                });

            modelBuilder.Entity("PizzAPIe.Data.Models.Order", b =>
                {
                    b.HasOne("PizzAPIe.Data.Models.Cheese", "Cheese")
                        .WithMany()
                        .HasForeignKey("CheeseID");

                    b.HasOne("PizzAPIe.Data.Models.Sauce", "Sauce")
                        .WithMany()
                        .HasForeignKey("SauceID");

                    b.HasOne("PizzAPIe.Data.Models.Size", "Size")
                        .WithMany()
                        .HasForeignKey("SizeID");

                    b.HasOne("PizzAPIe.Data.Models.Topping", "Topping")
                        .WithMany()
                        .HasForeignKey("ToppingID");
                });
#pragma warning restore 612, 618
        }
    }
}
